# Generated by Django 5.0.3 on 2024-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao_meses',
            field=models.IntegerField(),
        ),
    ]
