# Generated by Django 5.0.3 on 2024-03-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_curso_carga_horaria_total_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaSaber',
            new_name='AreaDosSabere',
        ),
        migrations.RenameModel(
            old_name='Avaliacao',
            new_name='Avaliacoe',
        ),
        migrations.RenameModel(
            old_name='Instituicao',
            new_name='Instituicoe',
        ),
        migrations.RenameModel(
            old_name='Ocupacao',
            new_name='Ocupacoe',
        ),
    ]
